"""Assurance tests for hash-locked Python tool installation identity."""

import base64
import hashlib
import os
import platform
from pathlib import Path

from app.adapters.bandit_adapter import BanditAdapter
from app.core import package_trust
from app.core.package_trust import (
    build_package_trust_record,
    verify_package_trust,
    write_package_trust_record,
)
from app.installers.tool_manifest import PINNED_TOOL_MANIFEST


def _record_digest(path: Path) -> str:
    digest = hashlib.sha256(path.read_bytes()).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii").rstrip("=")


def _create_fake_bandit_environment(tmp_path: Path, monkeypatch):
    venv_root = tmp_path / "tool-venvs"
    venv_dir = venv_root / "bandit"
    bin_dir = venv_dir / ("Scripts" if os.name == "nt" else "bin")
    site_packages = (
        venv_dir / "Lib" / "site-packages"
        if os.name == "nt"
        else venv_dir / "lib" / "python3.13" / "site-packages"
    )
    bin_dir.mkdir(parents=True)
    site_packages.mkdir(parents=True)
    monkeypatch.setenv("CYBERASSESS_TOOL_VENV_DIR", str(venv_root))

    interpreter = bin_dir / ("python.exe" if os.name == "nt" else "python")
    interpreter.write_bytes(b"managed interpreter")
    binary = bin_dir / ("bandit.exe" if os.name == "nt" else "bandit")
    binary.write_bytes(b"managed bandit executable")
    if os.name != "nt":
        binary.chmod(0o755)

    package_dir = site_packages / "bandit"
    package_dir.mkdir()
    package_file = package_dir / "__init__.py"
    package_file.write_bytes(b"__version__ = '1.7.8'\n")
    generated_bytecode = package_dir / "__pycache__" / "fixture.cpython-313.pyc"
    generated_bytecode.parent.mkdir()
    generated_bytecode.write_bytes(b"generated bytecode")
    dist_info = site_packages / "bandit-1.7.8.dist-info"
    dist_info.mkdir()
    metadata_file = dist_info / "METADATA"
    metadata_file.write_text(
        "Metadata-Version: 2.1\nName: bandit\nVersion: 1.7.8\n",
        encoding="utf-8",
    )
    record_file = dist_info / "RECORD"
    record_file.write_text(
        "\n".join(
            [
                f"bandit/__init__.py,sha256={_record_digest(package_file)},{package_file.stat().st_size}",
                "bandit/__pycache__/fixture.cpython-313.pyc,,",
                f"bandit-1.7.8.dist-info/METADATA,sha256={_record_digest(metadata_file)},{metadata_file.stat().st_size}",
                "bandit-1.7.8.dist-info/RECORD,,",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    lock_file = tmp_path / "bandit.lock"
    root_hash = PINNED_TOOL_MANIFEST["bandit"]["sha256_checksums"]["pypi_sdist"]
    lock_file.write_text(
        f"bandit==1.7.8 \\\n    --hash=sha256:{root_hash}\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(package_trust, "get_lock_path", lambda _tool: lock_file)
    return binary, package_file


def test_package_trust_binds_lock_distribution_and_executable(tmp_path, monkeypatch):
    binary, package_file = _create_fake_bandit_environment(tmp_path, monkeypatch)

    record = build_package_trust_record(
        tool_name="bandit",
        package_name="bandit",
        binary_name="bandit",
        binary=str(binary),
        installer_version="14.3.0",
    )
    write_package_trust_record(record, str(binary))

    assert verify_package_trust(
        tool_name="bandit",
        package_name="bandit",
        binary_name="bandit",
        approved_version="1.7.8",
        binary=str(binary),
    ) is True

    package_file.write_bytes(b"tampered package code\n")
    assert BanditAdapter().verify_managed_binary(str(binary)) is False


def test_package_trust_rejects_missing_record_and_unapproved_path(tmp_path, monkeypatch):
    binary, _ = _create_fake_bandit_environment(tmp_path, monkeypatch)
    adapter = BanditAdapter()

    assert adapter.verify_managed_binary(str(binary)) is False
    assert adapter.verify_managed_binary(str(tmp_path / "bandit")) is False


def test_hash_locked_requirements_accept_uv_continuation_lines():
    lock_path = Path(__file__).parents[2] / "backend" / "tool-requirements" / "sslyze.lock"

    requirements = package_trust.parse_locked_requirements(lock_path)

    assert requirements["sslyze"]["version"] == "5.2.0"
    assert all(requirement["hashes"] for requirement in requirements.values())


def test_hash_locked_requirements_honor_platform_markers(tmp_path):
    lock_path = tmp_path / "platform.lock"
    continuation = chr(92)
    lock_path.write_text(
        "\n".join(
            [
                f'only-on-never==1.0 ; sys_platform == "__never__" {continuation}',
                "    --hash=sha256:" + "a" * 64 + f" {continuation}",
                f"always==1.0 {continuation}",
                "    --hash=sha256:" + "b" * 64,
            ]
        ),
        encoding="utf-8",
    )

    requirements = package_trust.parse_locked_requirements(lock_path)

    assert "only-on-never" not in requirements
    assert requirements["always"]["hashes"] == ["b" * 64]


def test_standalone_trust_requires_manifest_bound_archive_and_exact_identity(tmp_path, monkeypatch):
    import json

    managed_dir = tmp_path / "managed-bin"
    managed_dir.mkdir()
    binary_name = "nuclei.exe" if os.name == "nt" else "nuclei"
    binary = managed_dir / binary_name
    binary.write_bytes(b"managed nuclei executable")
    if os.name != "nt":
        binary.chmod(0o755)
    manifest = PINNED_TOOL_MANIFEST["nuclei"]
    platform_name = "windows" if os.name == "nt" else "linux"
    architecture = "arm64" if platform.machine().lower() in {"arm64", "aarch64"} else "amd64"
    platform_key = f"{platform_name}_{architecture}"
    record = {
        "tool_id": "TOOL-NUCLEI",
        "tool_version": "v3.2.0",
        "artifact_filename": manifest["asset_names"][platform_key],
        "artifact_sha256": manifest["sha256_checksums"][platform_key],
        "executable_relative_path": binary.name,
        "executable_sha256": hashlib.sha256(binary.read_bytes()).hexdigest(),
        "platform": platform_name,
        "architecture": architecture,
        "installer_version": "14.3.0",
        "trust_status": "VALID",
        "claims": ["ARCHIVE_INTEGRITY_VERIFIED", "EXECUTABLE_INTEGRITY_VERIFIED"],
    }
    (managed_dir / f"{binary.name}.trust.json").write_text(json.dumps(record), encoding="utf-8")
    import app.core.binary_trust as binary_trust
    monkeypatch.setattr(binary_trust, "get_managed_bin_dir", lambda: managed_dir)

    assert binary_trust.verify_managed_binary_artifact("nuclei", str(binary), expected_version="3.2.0") is True

    record["artifact_sha256"] = "0" * 64
    (managed_dir / f"{binary.name}.trust.json").write_text(json.dumps(record), encoding="utf-8")
    assert binary_trust.verify_managed_binary_artifact("nuclei", str(binary), expected_version="3.2.0") is False


def test_direct_artifact_record_binds_managed_executable_to_manifest(tmp_path, monkeypatch):
    import app.core.binary_trust as binary_trust

    managed_dir = tmp_path / "managed-bin"
    managed_dir.mkdir()
    binary = managed_dir / "nuclei"
    binary.write_bytes(b"verified direct release executable")
    if os.name != "nt":
        binary.chmod(0o755)
    monkeypatch.setattr(binary_trust, "get_managed_bin_dir", lambda: managed_dir)

    binary_trust.write_direct_artifact_trust_record(
        "nuclei", str(binary), installer_version="14.3.0"
    )
    assert binary_trust.verify_managed_binary_artifact(
        "nuclei", str(binary), expected_version="3.2.0"
    ) is True

    binary.write_bytes(b"tampered direct release executable")
    assert binary_trust.verify_managed_binary_artifact(
        "nuclei", str(binary), expected_version="3.2.0"
    ) is False
